# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lerobot_pb2 as lerobot__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lerobot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """────────────────────────────────────────────────────────────
    1. Inference Service  (Desktop → Server)
    ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/lerobot.InferenceService/LoadModel',
                request_serializer=lerobot__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=lerobot__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/lerobot.InferenceService/UnloadModel',
                request_serializer=lerobot__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=lerobot__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/lerobot.InferenceService/ListModels',
                request_serializer=lerobot__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=lerobot__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.GetAction = channel.unary_unary(
                '/lerobot.InferenceService/GetAction',
                request_serializer=lerobot__pb2.ObservationRequest.SerializeToString,
                response_deserializer=lerobot__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GetActionStream = channel.unary_stream(
                '/lerobot.InferenceService/GetActionStream',
                request_serializer=lerobot__pb2.ObservationRequest.SerializeToString,
                response_deserializer=lerobot__pb2.ActionChunk.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """────────────────────────────────────────────────────────────
    1. Inference Service  (Desktop → Server)
    ────────────────────────────────────────────────────────────

    """

    def LoadModel(self, request, context):
        """Load a model onto the server GPU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Unload a model from GPU memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List currently loaded models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAction(self, request, context):
        """Single-step action prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionStream(self, request, context):
        """Streaming action prediction (for chunk-based policies like ACT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=lerobot__pb2.LoadModelRequest.FromString,
                    response_serializer=lerobot__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=lerobot__pb2.UnloadModelRequest.FromString,
                    response_serializer=lerobot__pb2.UnloadModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=lerobot__pb2.ListModelsRequest.FromString,
                    response_serializer=lerobot__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAction,
                    request_deserializer=lerobot__pb2.ObservationRequest.FromString,
                    response_serializer=lerobot__pb2.ActionResponse.SerializeToString,
            ),
            'GetActionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetActionStream,
                    request_deserializer=lerobot__pb2.ObservationRequest.FromString,
                    response_serializer=lerobot__pb2.ActionChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lerobot.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lerobot.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """────────────────────────────────────────────────────────────
    1. Inference Service  (Desktop → Server)
    ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.InferenceService/LoadModel',
            lerobot__pb2.LoadModelRequest.SerializeToString,
            lerobot__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.InferenceService/UnloadModel',
            lerobot__pb2.UnloadModelRequest.SerializeToString,
            lerobot__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.InferenceService/ListModels',
            lerobot__pb2.ListModelsRequest.SerializeToString,
            lerobot__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.InferenceService/GetAction',
            lerobot__pb2.ObservationRequest.SerializeToString,
            lerobot__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lerobot.InferenceService/GetActionStream',
            lerobot__pb2.ObservationRequest.SerializeToString,
            lerobot__pb2.ActionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrainingServiceStub(object):
    """────────────────────────────────────────────────────────────
    2. Training Service  (Desktop → Server)
    ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEpisode = channel.stream_unary(
                '/lerobot.TrainingService/StreamEpisode',
                request_serializer=lerobot__pb2.EpisodeFrame.SerializeToString,
                response_deserializer=lerobot__pb2.EpisodeUploadResponse.FromString,
                _registered_method=True)
        self.StartTraining = channel.unary_unary(
                '/lerobot.TrainingService/StartTraining',
                request_serializer=lerobot__pb2.TrainingRequest.SerializeToString,
                response_deserializer=lerobot__pb2.TrainingJobResponse.FromString,
                _registered_method=True)
        self.GetTrainingStatus = channel.unary_unary(
                '/lerobot.TrainingService/GetTrainingStatus',
                request_serializer=lerobot__pb2.TrainingStatusRequest.SerializeToString,
                response_deserializer=lerobot__pb2.TrainingStatusResponse.FromString,
                _registered_method=True)
        self.StreamTrainingLogs = channel.unary_stream(
                '/lerobot.TrainingService/StreamTrainingLogs',
                request_serializer=lerobot__pb2.TrainingStatusRequest.SerializeToString,
                response_deserializer=lerobot__pb2.TrainingLog.FromString,
                _registered_method=True)
        self.StopTraining = channel.unary_unary(
                '/lerobot.TrainingService/StopTraining',
                request_serializer=lerobot__pb2.TrainingStatusRequest.SerializeToString,
                response_deserializer=lerobot__pb2.TrainingJobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/lerobot.TrainingService/ListJobs',
                request_serializer=lerobot__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=lerobot__pb2.ListJobsResponse.FromString,
                _registered_method=True)


class TrainingServiceServicer(object):
    """────────────────────────────────────────────────────────────
    2. Training Service  (Desktop → Server)
    ────────────────────────────────────────────────────────────

    """

    def StreamEpisode(self, request_iterator, context):
        """Upload a single episode frame stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Trigger training job on uploaded dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStatus(self, request, context):
        """Poll training status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrainingLogs(self, request, context):
        """Stream live training logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTraining(self, request, context):
        """Stop a running training job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """List all training jobs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEpisode': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamEpisode,
                    request_deserializer=lerobot__pb2.EpisodeFrame.FromString,
                    response_serializer=lerobot__pb2.EpisodeUploadResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=lerobot__pb2.TrainingRequest.FromString,
                    response_serializer=lerobot__pb2.TrainingJobResponse.SerializeToString,
            ),
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=lerobot__pb2.TrainingStatusRequest.FromString,
                    response_serializer=lerobot__pb2.TrainingStatusResponse.SerializeToString,
            ),
            'StreamTrainingLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrainingLogs,
                    request_deserializer=lerobot__pb2.TrainingStatusRequest.FromString,
                    response_serializer=lerobot__pb2.TrainingLog.SerializeToString,
            ),
            'StopTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTraining,
                    request_deserializer=lerobot__pb2.TrainingStatusRequest.FromString,
                    response_serializer=lerobot__pb2.TrainingJobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=lerobot__pb2.ListJobsRequest.FromString,
                    response_serializer=lerobot__pb2.ListJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lerobot.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lerobot.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """────────────────────────────────────────────────────────────
    2. Training Service  (Desktop → Server)
    ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def StreamEpisode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/lerobot.TrainingService/StreamEpisode',
            lerobot__pb2.EpisodeFrame.SerializeToString,
            lerobot__pb2.EpisodeUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.TrainingService/StartTraining',
            lerobot__pb2.TrainingRequest.SerializeToString,
            lerobot__pb2.TrainingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.TrainingService/GetTrainingStatus',
            lerobot__pb2.TrainingStatusRequest.SerializeToString,
            lerobot__pb2.TrainingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrainingLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lerobot.TrainingService/StreamTrainingLogs',
            lerobot__pb2.TrainingStatusRequest.SerializeToString,
            lerobot__pb2.TrainingLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.TrainingService/StopTraining',
            lerobot__pb2.TrainingStatusRequest.SerializeToString,
            lerobot__pb2.TrainingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.TrainingService/ListJobs',
            lerobot__pb2.ListJobsRequest.SerializeToString,
            lerobot__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GenericInferenceServiceStub(object):
    """────────────────────────────────────────────────────────────
    3. Generic Inference Service  (범용 JSON RPC — baseline 공용)
    ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/lerobot.GenericInferenceService/Infer',
                request_serializer=lerobot__pb2.GenericRequest.SerializeToString,
                response_deserializer=lerobot__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.InferStream = channel.unary_stream(
                '/lerobot.GenericInferenceService/InferStream',
                request_serializer=lerobot__pb2.GenericRequest.SerializeToString,
                response_deserializer=lerobot__pb2.GenericResponse.FromString,
                _registered_method=True)


class GenericInferenceServiceServicer(object):
    """────────────────────────────────────────────────────────────
    3. Generic Inference Service  (범용 JSON RPC — baseline 공용)
    ────────────────────────────────────────────────────────────

    """

    def Infer(self, request, context):
        """단일 요청 / 단일 응답
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request, context):
        """서버 → 클라이언트 스트리밍 (대용량 응답 / 점진적 결과)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenericInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=lerobot__pb2.GenericRequest.FromString,
                    response_serializer=lerobot__pb2.GenericResponse.SerializeToString,
            ),
            'InferStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=lerobot__pb2.GenericRequest.FromString,
                    response_serializer=lerobot__pb2.GenericResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lerobot.GenericInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lerobot.GenericInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenericInferenceService(object):
    """────────────────────────────────────────────────────────────
    3. Generic Inference Service  (범용 JSON RPC — baseline 공용)
    ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.GenericInferenceService/Infer',
            lerobot__pb2.GenericRequest.SerializeToString,
            lerobot__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lerobot.GenericInferenceService/InferStream',
            lerobot__pb2.GenericRequest.SerializeToString,
            lerobot__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """────────────────────────────────────────────────────────────
    4. Health Check
    ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/lerobot.HealthService/Ping',
                request_serializer=lerobot__pb2.PingRequest.SerializeToString,
                response_deserializer=lerobot__pb2.PingResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """────────────────────────────────────────────────────────────
    4. Health Check
    ────────────────────────────────────────────────────────────

    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=lerobot__pb2.PingRequest.FromString,
                    response_serializer=lerobot__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lerobot.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lerobot.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """────────────────────────────────────────────────────────────
    4. Health Check
    ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.HealthService/Ping',
            lerobot__pb2.PingRequest.SerializeToString,
            lerobot__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
